SELECT * FROM EMP;

SELECT EMPNO , ENAME , SAL FROM EMP;	--사원이름,번호,월급 조회
SELECT ENAME AS "이름" , SAL AS "월급" FROM EMP;	--큰따옴표는 식별자
-- 사원번호, 사원이름, 월급, 연봉을 구하고 컬럼명은 사원번호, 사원이름, 월급, 연봉으로 조회

SELECT EMPNO AS "사원번호", ENAME AS "사원이름", 
SAL AS "월급", SAL*12 AS "연봉" FROM EMP;

SELECT DISTINCT JOB FROM EMP;			--중복데이터 제거
SELECT DISTINCT JOB , DEPTNO FROM EMP;
SELECT ALL JOB , DEPTNO FROM EMP;

SELECT 'ABC' FROM DUAL;
SELECT 2+3 FROM DUAL;
SELECT 'ABC',2+3 FROM DUAL;
SELECT 1+'5' FROM DUAL;
SELECT '1'+'5' FROM DUAL;
SELECT 1 || '5' FROM DUAL;

--사원명과 업무로 연결(SMITH, CLERK)표시하고 컬럼명은 EMPLOYEE AND JOB으로 표시
SELECT '('||ENAME||','||JOB||')' AS "EMPLOYEE AND JOB" FROM EMP;

--사원별 연간 총수입을 컬럼명 연간총수입으로 바꿔서 조회
SELECT ENAME AS "사원", SAL*12+COMM AS "연간총수입" FROM EMP;

SELECT * FROM EMP;
SELECT * FROM EMP ORDER BY SAL;			--오름차순 정렬
SELECT * FROM EMP ORDER BY EMPNO;		--오름차순 정렬
SELECT * FROM EMP ORDER BY SAL DESC;	--내림차순 정렬

/*----------------------------------------------------------*/
--조건을 추가하는 WHERE
SELECT * FROM EMP WHERE EMPNO = 7876;
--사원번호 7900인 사원명,업무,급여 출력
SELECT ENAME, JOB, SAL FROM EMP WHERE EMPNO = 7900;
--SMITH의 사원명, 부서, 월급 출력
SELECT ENAME, JOB, SAL FROM EMP WHERE ENAME = 'SMITH';
--월급에 해당하는 사원출력
SELECT * FROM EMP WHERE SAL = 3000;
--월급에 해당하지 않는 사원출력
SELECT * FROM EMP WHERE SAL != 3000;
SELECT * FROM EMP WHERE SAL ^= 4000;
SELECT * FROM EMP WHERE SAL <> 5000;
SELECT * FROM EMP WHERE NOT SAL = 5000;
--첫글자가 'M'과 같거나 큰 문자열 출력
SELECT * FROM EMP WHERE ENAME >= 'M';
--월급이 2500 이상이고 3000미만인 사원과 입사일 그리고 월급조회
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE SAL<3000 AND SAL>=2500;
SELECT * FROM EMP WHERE SAL BETWEEN 2500 AND 3000;	--2500이상3000이하
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2500 AND 3000; --제외
--81년 5월 1일과 81년 12월 3일 사이에 입사한 사원, 급여, 입사일 조회
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE HIREDATE BETWEEN
TO_DATE('19810501','YYYYMMDD') AND TO_DATE('19811203','YYYYMMDD');
--87년도 입사한 사원, 급여, 입사일 조회
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE HIREDATE BETWEEN
TO_DATE('19870101','YYYYMMDD') AND TO_DATE('19871231','YYYYMMDD');
--직업이 MANAGER, 'CLERK', 'SALESMAN'
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'CLERK'OR
JOB = 'SALESMAN';
SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK','SALESMAN');
--사원번호 7566,7782,7934인 사원을 제외한 사원번호, 급여, 입사일 조회
SELECT ENAME, HIREDATE, SAL FROM EMP WHERE 
EMPNO NOT IN (7566,7782,7934);
--부서번호 30에서 근무하고 월 2000달러 이하를 받는 81년 5월 1일 이전에 입사한 사원이름, 
--급여, 부서번호, 입사일 조회
SELECT ENAME, DEPTNO , HIREDATE, SAL FROM EMP WHERE DEPTNO IN (30) 
AND SAL <= 2000 AND HIREDATE BETWEEN TO_DATE('19800101','YYYYMMDD')
AND TO_DATE('19810501','YYYYMMDD');
--부서번호:10또는30, 월급:2000~5000 의 사원명, 급여, 부서번호
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE DEPTNO IN (10, 30) AND
SAL BETWEEN 2000 AND 5000;
--직업: MANAGER OR SALESMAN 급여: 1600,2975,2850가 아닌 사원정보
SELECT ENAME, JOB, SAL, HIREDATE  FROM EMP WHERE 
JOB IN ('MANAGER', 'SALESMAN') AND SAL NOT IN (1600,2975,2850);
/*-------------------------------------------------------------*/
SELECT * FROM EMP WHERE ENAME LIKE 'S%';	--첫글자가'S'인 문자열 출력
SELECT * FROM EMP WHERE ENAME LIKE '_L%';	--두번째 글자가 'L'인 문자열 출력
--1. 사원이름중에 'S'가 포함되지않는 부서번호 20인 사원의 이름, 부서번호 조회
--2. 1981.6.1 ~ 1981.12.31 입사자 중 부서명이 30인 사원의 부서번호, 사원명,
--직업, 입사일 출력(입사일 오름차순)
SELECT ENAME, DEPTNO FROM EMP WHERE ENAME NOT LIKE '%S%' AND 
DEPTNO = 20;
SELECT DEPTNO, ENAME, JOB, HIREDATE FROM EMP WHERE HIREDATE BETWEEN 
TO_DATE('19810601','YYYYMMDD') AND TO_DATE('19811231','YYYYMMDD')
AND DEPTNO = 30;
--사원 이름중 A와E가 있는 사원조회
SELECT * FROM EMP WHERE ENAME LIKE '%A%' AND ENAME LIKE '%E%';

SELECT * FROM EMP WHERE COMM = NULL;		--NULL은 비교연산자 사용불가
SELECT ENAME , SAL*12 + COMM, COMM FROM EMP;
SELECT * FROM EMP WHERE COMM IS NULL;		--NULL인 열찾기
--사수가 있는 사원출력
SELECT * FROM EMP WHERE MGR IS NOT NULL;
--수당에서 0을 제외한 사원조회
SELECT * FROM EMP WHERE NOT COMM = 0 OR COMM IS NULL;