--오라클 내장함수
--1. 단일행 함수:하나의 데이터를 이용하여 변환 또는 계산을 수행
--https://docs.oracle.com/database/121/SQLRF/functions002.htm#SQLRF51178
--2. 집계 함수: 데이터를 집계하여 계산 처리를 수행하는 함수
--https://docs.oracle.com/database/121/SQLRF/functions003.htm#SQLRF20035
--3. 분석 함수: 행 그룹을 기반으로 집계 값을 계산
--https://docs.oracle.com/database/121/SQLRF/functions004.htm#SQLRF06174

SELECT ENAME, UPPER(ENAME), LOWER(ENAME)  FROM EMP;	  --대소문자
SELECT ENAME, INITCAP(ENAME) FROM EMP; 				  --첫글자를 대문자로


SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO=10
UNION 			--합집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO=20;
--열의 갯수와 데이터유형이 같아야한다
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP WHERE DEPTNO=10
UNION 			--합집합
SELECT EMPNO, ENAME, DEPTNO ,SAL FROM EMP WHERE DEPTNO=20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO=10
UNION 			--합집합
SELECT SAL, JOB, DEPTNO ,SAL FROM EMP WHERE DEPTNO=20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
MINUS			--차집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
INTERSECT		--교집합
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

SELECT ENAME, LENGTH(ENAME) FROM EMP;

--이름 글자가 5글자 이상인 사원출력
SELECT ENAME, LENGTH(ENAME) FROM EMP WHERE LENGTH(ENAME) >= 5;
--LENGTH:문자길이, LENGTHB:바이트크기
SELECT LENGTH('오라클'), LENGTHB('오라클') FROM dual; 

--문자열 일부를 추출 substr(컬럼,시작점,몇번째까지) 함수 
SELECT JOB, SUBSTR(JOB,1,2), SUBSTR(JOB,3,2), SUBSTR(JOB,5)
FROM EMP; 
--모든사원의 이름을 세번째부터 출력
SELECT ENAME, SUBSTR(ENAME,3) FROM EMP; 
--특정문자 위치를 찾는 instr함수
SELECT INSTR('HELLO, ORACLE!','L') AS INSTR1, --처음부터 L의 위치찾기
INSTR('HELLO, ORACLE!','L',5) AS INSTR2,	  --5번째(O)부터 L을 찾기
INSTR('HELLO, ORACLE!','L',2,2) AS INSTR3     --2번째부터 2번째로 나오는 L찾기
FROM DUAL; 
--사원이름중에 'S'가 들어가 있는 정보출력
SELECT * FROM EMP WHERE INSTR(ENAME ,'S') > 0;
SELECT * FROM EMP WHERE ENAME LIKE '%S%';
--문자변환 REPLACE 함수 , REPLACE(문자열,찾는문자(필수),대체문자(선택))
SELECT '010-1234-5678' AS REPLACE1,
REPLACE('010-1234-5678','-',' ') AS REPLACE2,	
REPLACE('010-1234-5678','-') AS REPLACE3
FROM DUAL;
--빈공간 메우는 LPAD 함수, LPAD(문자열, 전체자리수, 빈자리채울문자)
SELECT 'ORACLE',
LPAD('ORACLE',10,'#') AS LPAD1,
RPAD('ORACLE',10,'*') AS RPAD1,
LPAD('ORACLE',10) AS LPAD2,
RPAD('ORACLE',10) AS RPAD2
FROM DUAL;

--주민번호, 전화번호의 끝에 7자리, 4자리를 '*'로 처리
SELECT
RPAD('123456-',14,'*') AS RPADNUM1,
RPAD('010-1234-',13,'*') AS RPADNUM2
FROM DUAL;

--특정문자를 지우는 TRIM, LTRIM, RTRIM 함수
SELECT '[' || TRIM(' __OREACLE__ ') || ']' AS TRIM,  --앞뒤의 공백삭제
'[' || TRIM (LEADING FROM' __OREACLE__ ') || ']' AS TRIM_LEADING,
'[' || TRIM (TRAILING FROM' __OREACLE__ ') || ']' AS TRIM_TRAILING,
'[' || TRIM (BOTH FROM' __OREACLE__ ') || ']' AS TRIM_BOTH
FROM DUAL;

--반올림 함수 ROUND
SELECT ROUND(1234.5678),
ROUND(1234.5678, 0),
ROUND(1234.56578, 1),
ROUND(1234.5678, -1),		--자연수 첫째자리 반올림
ROUND(1234.5678, -2)
FROM DUAL;
--버림하는 함수 TRUNC
SELECT TRUNC(1234.5678),
TRUNC(1234.5678,0),
TRUNC(1234.5678,1),
TRUNC(1234.5678,-1)
FROM DUAL;
--나머지를 구하는 함수 MOD
SELECT MOD(15,2), MOD(10,2), MOD(11,2) FROM DUAL;
--각 사원별 시급을 계산하여 부서번호, 사원이름, 시급을 출력
--1. 한달근무일시 20일, 하루 근무시간은 8시간
--2. 부서별로 오름차순으로 정렬
--3. 시급은 소수 2자리까리
--4. 시급이 높은순으로 출력
SELECT * FROM EMP;
SELECT ENAME , ROUND(SAL/20/8,2) AS "시급", DEPTNO 
FROM EMP ORDER BY DEPTNO , "시급" DESC;
--날짜 함수
SELECT SYSDATE AS NOW,
SYSDATE -1 AS YESTERDAY,
SYSDATE +1 AS TOMORROW
FROM DUAL;

SELECT SYSDATE , ADD_MONTHS(SYSDATE, 3) 
FROM DUAL;
--입사10주년인 사원들 출력(사원번호, 사원이름, 입사일)
SELECT * FROM EMP;
SELECT EMPNO  ,ENAME , HIREDATE , 
ADD_MONTHS(HIREDATE, 120) AS "입사 10주년"
FROM EMP;
--두 날짜간의 개월차
SELECT EMPNO, ENAME, HIREDATE, SYSDATE, 
MONTHS_BETWEEN(HIREDATE,SYSDATE) AS MONTHS1,
MONTHS_BETWEEN(SYSDATE,HIREDATE) AS MONTHS2,
TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS MONTHS3
FROM EMP;
--요일, 마지막날짜
SELECT SYSDATE , 
NEXT_DAY(SYSDATE, '금요일'),
LAST_DAY(SYSDATE)	--특정날짜가 속한 마지막 날
FROM DUAL;

SELECT SYSDATE , 
	ROUND(SYSDATE,'CC') AS FORMAT_CC,
	ROUND(SYSDATE,'YYYY') AS FORMAT_YYYY
FROM DUAL;
--형 변환함수
SELECT EMPNO, ENAME, EMPNO+'500' FROM EMP 
WHERE ENAME = 'SCOTT';

--CC: 세기, YYYY: 연도, YY:연도(2), MM:월(약어), MONTH:월(전체), 
--DD:일, DDD:365일, DY:요일(약어), DAY(풀어), W:주,
--HH:24시간, HH/HH12:12시간, M1:분, SS:초, AM/PM/A.M/P.M:오전,오후
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS "현재날짜시간" 
FROM DUAL;

SELECT SYSDATE ,
TO_CHAR(SYSDATE, 'MM') AS MM,
TO_CHAR(SYSDATE, 'MON') AS MON,
TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
TO_CHAR(SYSDATE, 'DD') AS DD,
TO_CHAR(SYSDATE, 'DY') AS DY,
TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;
SELECT SYSDATE ,
TO_CHAR(SYSDATE, 'MM') AS MM,
TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_K,
TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = JAPANESE') AS MON_J,
TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = ENGLISH') AS DD_E,
TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = KOREAN') AS DY_K,
TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH') AS DAY_E
FROM DUAL;
SELECT SYSDATE ,
TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS,
TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HH12MISS_AM,
TO_CHAR(SYSDATE, 'HH:MI,SS P.M.') AS HHMISS_PM
FROM DUAL;
SELECT TO_DATE('2019-04-04','YYYY-MM-DD') AS TODATE, 
TO_DATE('20100301','YYYY-MM-DD') AS TODATE2
FROM DUAL;
-- 1981년 12월 1일 이후에 입사한 사원정보 출력
SELECT * FROM EMP;
SELECT DEPTNO, ENAME, HIREDATE  FROM EMP WHERE 
HIREDATE > TO_DATE('1981-12-01','YYYY-MM-DD');