-- DDL(데이터 정의어) - CREATE/ALTER/DROP
-- DML(데이터 조작어) - SELECT / INSERT / DELETE / UPDATAE
-- DCL(데이터 제어) - GRANT/REVOKE

CREATE TABLE ex2_2(             --ex2_2 테이블 생성
	COLUMN1	char(20),
	COLUMN2	varchar2(20),
	COLUMN3	varchar2(20),
	COLUMN4	NUMBER,
	COLUMN5	Date
);

INSERT INTO "ex2_2"(COLUMN1, COLUMN2) VALUES ('abc','abc');     --ex2_2 테이블에 값 넣기

SELECT COLUMN1, LENGTH(COLUMN1) AS len1,        --LENGTH()란 컬럼길이를 반환하는 함수
	   COLUMN2, LENGTH(COLUMN2) AS len2         --LENGTH(COLUMN2)을 len2로 컬럼명 변환
FROM "ex2_2";

DROP TABLE EX2_2 ;              --ex2_2 테이블 삭제

CREATE TABLE EX2_2(
	COLUMN1 varchar2(3),
	COLUMN2 varchar2(3 byte),
	COLUMN3 varchar2(3 char)
);

INSERT INTO EX2_2 VALUES('ABC','ABC','ABC');

SELECT * FROM EX2_2;

SELECT COLUMN1, LENGTH (COLUMN1) AS len1,
 	    COLUMN2, LENGTH (COLUMN2) AS len2,
 	    COLUMN3, LENGTH (COLUMN3) AS len3 FROM EX2_2;
 	   
INSERT INTO EX2_2 (COLUMN3)VALUES('홍길동');

SELECT COLUMN3, LENGTH(COLUMN3) AS len3, LENGTHB(COLUMN3) AS bytelen FROM EX2_2;

CREATE TABLE ex2_3(
	col_int	INTEGER,
	col_dec	DECIMAL,
	col_num	NUMBER
);

SELECT COLUMN_id, COLUMN_name, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLS WHERE TABLE_name = 'EX2_3'
ORDER BY COLUMN_ID;         

CREATE TABLE ex2_5(
col_date	DATE,
col_timestamp	TIMESTAMP
);

INSERT INTO EX2_5 VALUES (SYSDATE, SYSTIMESTAMP);
SELECT * FROM EX2_5;

CREATE TABLE EX2_6(
COL_NULL	VARCHAR2(10),
COL_NOT_NULL	VARCHAR2(10) NOT NULL
);
INSERT INTO EX2_6 VALUES ('AA','BB');

SELECT CONSTRAINT_name, CONSTRAINT_type, TABLE_name, SEARCH_condition
FROM USER_CONSTRAINTS WHERE TABLE_name = 'EX2_6';

CREATE TABLE ex2_7(
COL_UNIQUE_NULL	VARCHAR2(10) UNIQUE,
COL_UNIQUE_NNULL VARCHAR2(10) UNIQUE NOT NULL,
COL_UNIQUE VARCHAR2(10),
CONSTRAINTS unique_nm1 UNIQUE (COL_UNIQUE)
);

SELECT CONSTRAINT_name, CONSTRAINT_type, TABLE_name, SEARCH_condition
FROM USER_CONSTRAINTS WHERE TABLE_name = 'EX2_7';